// This file is automatically generated by a script.
import { InlineAnnotation } from "@atjson/document";

export class $text extends InlineAnnotation<{
  bold: unknown;
  italic: unknown;
  linkHref: unknown;
}> {
  static vendorPrefix = "ckeditor";
  static type = "$text";
}
