// This file is automatically generated by a script.
import { BlockAnnotation } from "@atjson/document";

export class Heading3 extends BlockAnnotation {
  static vendorPrefix = "ckeditor";
  static type = "heading3";
}
