// This file is automatically generated by a script.
import { BlockAnnotation } from "@atjson/document";

export class Image extends BlockAnnotation<{
  alt: unknown;
  src: unknown;
  srcset: unknown;
  uploadId: unknown;
  uploadStatus: unknown;
  imageStyle: unknown;
}> {
  static vendorPrefix = "ckeditor";
  static type = "image";
}
