// This file is automatically generated by a script.
import { BlockAnnotation } from "@atjson/document";

export class ListItem extends BlockAnnotation<{
  listType: unknown;
  listIndent: unknown;
}> {
  static vendorPrefix = "ckeditor";
  static type = "listItem";
}
