// This file is automatically generated by a script.
import { BlockAnnotation } from "@atjson/document";

export class Media extends BlockAnnotation<{
  url: unknown;
}> {
  static vendorPrefix = "ckeditor";
  static type = "media";
}
