// This file is automatically generated by a script.
import { BlockAnnotation } from "@atjson/document";

export class Paragraph extends BlockAnnotation {
  static vendorPrefix = "ckeditor";
  static type = "paragraph";
}
