// This file is automatically generated by a script.
import { InlineAnnotation } from "@atjson/document";

export class SoftBreak extends InlineAnnotation {
  static vendorPrefix = "ckeditor";
  static type = "softBreak";
}
