// This file is automatically generated by a script.
import { BlockAnnotation } from "@atjson/document";

export class Table extends BlockAnnotation<{
  headingRows: unknown;
  headingColumns: unknown;
}> {
  static vendorPrefix = "ckeditor";
  static type = "table";
}
