// This file is automatically generated by a script.
import { BlockAnnotation } from "@atjson/document";

export class TableRow extends BlockAnnotation {
  static vendorPrefix = "ckeditor";
  static type = "tableRow";
}
