// This file is automatically generated by a script.
import { BlockAnnotation } from "@atjson/document";

export class TableCell extends BlockAnnotation<{
  colspan: unknown;
  rowspan: unknown;
}> {
  static vendorPrefix = "ckeditor";
  static type = "tableCell";
}
