// This file is automatically generated by a script.
import CKEditorSource, { CK } from "../../src";
import * as annotations from "./annotations";

export default class CKEditorTestSource extends CKEditorSource {
  static fromRaw(model: CK.Model, rootName = "main") {
    return new this(this.fromModel(model, rootName));
  }

  static schema = [...Object.values(annotations)];
}
