// This file is automatically generated by a script.
import CKEditorSource, { CK } from "../../src";
import * as annotations from "./annotations";

export default class CKEditorTestSource extends CKEditorSource {
  static fromRaw(doc: CK.Document | CK.DocumentFragment, rootName?: string) {
    return new this(this.fromDocument(doc, rootName));
  }

  static schema = [...Object.values(annotations)];
}
