---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - typescript
      - javascript
  tslint:
    enabled: true
    channel: beta
  fixme:
    enabled: true
ratings:
  paths:
  - "**.ts"
  - "**.tsx"
  - "**.js"
  - "**.jsx"
exclude_paths:
- packages/**/dist
- packages/**/node_modules
include_paths:
- packages/**/src/*
