name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "22.15.0"
      - name: Install
        run: |
          npm ci
      - name: 🔎 ESLint
        run: |
          npm run lint
      - name: 🃏 Jest
        run: |
          npm test -- --no-cache --coverage --maxWorkers=4
      - name: ✅ Type Check
        run: |
          npm run typecheck
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "22.15.0"
      - name: Docs
        run: |
          npm ci
          npm run build
          cd website
          npm ci
          npm run build
